local ignoreList = {""
-- ,"Invalid"
-- ,"Error"
,"FighterCoin_Add"
,"DriveTicket_Add"
,"Item_Add"
,"Title_Add"
-- ,"Gallery_ContentsOpen"
-- ,"Tournament_EventNotice"
-- ,"Tournament_CabinetNotice"
-- ,"FighterList_Follow"
-- ,"FighterList_FollowCancel"
-- ,"FighterList_FriendRequest"
-- ,"FighterList_FriendRequestCancel"
-- ,"FighterList_FriendRequestReceive"
-- ,"FighterList_FriendRequestApproval"
-- ,"FighterList_FriendCancel"
-- ,"FighterList_Block"
-- ,"FighterList_BlockCancel"
-- ,"FightersClub_Create"
-- ,"FightersClub_JoinRequest"
-- ,"FightersClub_JoinRequestAccepted"
-- ,"FightersClub_JoinRequestApprove"
-- ,"FightersClub_JoinRequestReject"
 ,"Replay_ReplayListAdd"
-- ,"Replay_ReplayListDelete"
-- ,"Replay_ReplayListAddMulti"
-- ,"Replay_ReplayListDeleteMulti"
,"Challgen_MissionComplete"
,"Kudos_PointAchieve"
,"BattlePass_TierAchieve"
-- ,"Arcade_ScoreRankingAdd"
-- ,"CustomRoom_SettingChanged"
-- ,"CustomRoom_InvitationReceive"
-- ,"Matching_EnterExclusionZone"
-- ,"Contest_Vote"
-- ,"FightersClub_InviteSend"
-- ,"FightersClub_JoinRequestCancel"
-- ,"FightersClub_JoinRequestApproveMulti"
-- ,"FightersClub_JoinRequestRejectMulti"
-- ,"FightersClub_JoinRequestCancelMulti"
-- ,"Patch_Found"
-- ,"Patch_Downloading"
-- ,"Patch_DownloadFinish"
-- ,"FightersClub_ClubDelete"
-- ,"FightersClub_ClubLeave"
-- ,"FightersClub_SettingMainClub"
-- ,"FightersClub_UniformReceive"
-- ,"FightersClub_MyClubSettingDecide"
-- ,"FightersClub_MyClubEmblemChange"
-- ,"FightersClub_ForumEmblemAccept"
-- ,"FightersClub_MyClubFlyerChagnge"
-- ,"FightersClub_ForumFlyerAccept"
-- ,"FightersClub_SubLeaderAppoint"
-- ,"FightersClub_SubLeaderDismiss"
-- ,"FightersClub_LeaderDelegate"
-- ,"FightersClub_MemberKick"
-- ,"FightersClub_InviteCancel"
-- ,"FightersClub_ClubJoin"
-- ,"FightersClub_InviteRefuse"
-- ,"FighterList_FriendRequestReject"
-- ,"Matching_ErrorOccurred"
-- ,"CapcomId_LinkFinish"
-- ,"BattleHub_Restrict"
-- ,"Tournament_ProgressNotice"
-- ,"Tournament_CabinetReserveProgressNotice"
-- ,"Contest_NewRewardFound"
-- ,"CharacterRental_Expired"
-- ,"Tournament_DiscardEntryBySystem"
-- ,"Tournament_DiscardEntryByAllowCrossPlay"
-- ,"Matching_CabinetLeaveFailed"
-- ,"CharacterRental_RentalFighterUse"
-- ,"CharacterRental_OverlapMaintenance"
-- ,"CharacterRental_RestrictTournament"
-- ,"Tournament_NoticeUseTornament"
-- ,"CustomRoom_HostChanged"
-- ,"CustomRoom_WinCountReset"
-- ,"OnlineShop_Buy"
-- ,"Tournament_CabinetLeaveNotAllowed"
-- ,"MasterPose_Add"
-- ,"Tournament_ErrorOccured"
-- ,"Training_MatchingSettingOpenFailedByCabinetMatchingWaiting"
-- ,"Common_MutePlayer"
-- ,"BattleHub_RestrictNowCabinetWaiting"
-- ,"Tournament_FinishByTimeout"
-- ,"Xbox_AccountName"
-- ,"Tournament_ReserveCancelByNearOpen"
-- ,"Tournament_ReserveCancelByCabinetWillUse"
-- ,"Cabinet_ReserveCancelByBlocked"
-- ,"Steam_InviteOverlayNotSupported"
-- ,"AvatarPose_Add"
-- ,"BattleHub_RandomSpectateNotFound"
-- ,"BattleHub_FightCancelByTimeout"
-- ,"BattleHub_ReplayEndByTournamentStart"
-- ,"Xbox_CrossPlaySupportGameModeNotice"
-- ,"CustomRoom_PlayerJoin"
-- ,"CustomRoom_PlayerLeave"
-- ,"FightersClub_ScoutReceive"
-- ,"Common_ReportPlayer"
-- ,"Training_MatchingSettingOpenFailedByOffline"
-- ,"Cabinet_ReserveByJoinFailed"
-- ,"Title_CampaignAdd"
-- ,"OnlineTeamBattle_SpectateEndByTimeOver"
-- ,"MusicPlayer_PlayNg"
-- ,"MusicPlayer_PlaySkip"
-- ,"MusicPlayer_PlayListStop"
-- ,"BattleHub_EventSwitchDisconnectNotice"
-- ,"Item_ContainLimitOver"
-- ,"CharacterRental_PlayEndAndTransitionByExpired"
-- ,"Matching_MasterRateGranted"
-- ,"CharacterRental_PlayEndAndTransitionByExpiredOnOffline"
-- ,"Item_SkipReceiveByContainLimitOver"
,"BattlePass_ReceivableRewardExist"
-- ,"BattleHub_AccessRestrictByCabinetReserve"
-- ,"Item_DiscardByContainLimitOver"
-- ,"Raid_DailyAttackPointLimitNotice"
-- ,"FighterCoin_WarnExpiration"
-- ,"Raid_GetAttackPoint"
-- ,"Raid_UpdateMaxAttackDamage"
-- ,"Raid_UpdateMaxGroupAttackDamage"
-- ,"Raid_ReceivablePersonalRewardExist"
-- ,"EventCode_UseCode"
-- ,"FightersClub_MyClubNameChange"
-- ,"RivalAI_LearningDataNotFound"
-- ,"Cabinet_LuckyTimeBegin"
-- ,"Cabinet_LuckyTimeEnd"
-- ,"Training_DummyInputTypeInvalid"
-- ,"Raid_ConsecutiveFightLimitOver"
-- ,"CustomRoom_ProhibitChangeCharacterSettingWhenReconnecting"
-- ,"CustomRoom_OneOnOneCabinetNotExistForReconnect"
-- ,"Ounce_NfcReadSuccess"
-- ,"Ounce_NfcReadSuccessPartially"
-- ,"Ounce_ControllerDisconnected"
-- ,"Ounce_NfcLoginFollowFail"
-- ,"Ounce_NfcLoginFriendRequestFail"
-- ,"Ounce_LocalMatchLogout"
}

local retval = {}
for k,v in ipairs(ignoreList) do
    table.insert(retval,sdk.find_type_definition("app.AppDefine.TickerData"):create_instance():get_field(v))
end
return retval